### ISSUE TITLE
Report and/or Suggestion modals open on postback of actions

### ISSUE THREAD

**Issue by Vaneryn** [Vaneryn/RojakJelah#26]
In Dictionary page, if Report or Suggestion modal is closed using the "X" button, the next time a postback occurs the Report or Suggestion modal will appear.

**Comment by Kyewn** [comment]
cant re-pro

**Comment by Vaneryn** [comment]
**Steps to reproduce:**
1. In `master` branch
2. Open Report/Suggestion modal
3. Fail submit with errors (for some reason only happens after submit)
4. Close using "X" button
5. Attempt any other event that causes postback (e.g. search)
6. Closed modal reappears

Fix implemented in `w13_01_dictionary-bugs`.

**Comment by Kyewn** [comment]
LGTM

**Comment by DreamDeshi** [comment]
It's fine to me.
