### ISSUE TITLE
Account issues

### ISSUE THREAD

**Issue by Kyewn** [Vaneryn/RojakJelah#6]
- Cannot register account with valid password format: Oowu.12345 (period not recognized as symbol)
- Need to insert an admin account to user table so we can use to test stuff instead of the system account.

**Comment by Vaneryn** [comment]
> * Cannot register account with valid password format: Oowu.12345 (period not recognized as symbol)

Noice catch, I actually missed out a bunch of symbols not just period, please test again.
Changes are implemented in 'w08_04_simplify-dbconnection'.

> * Need to insert an admin account to user table so we can use to test stuff instead of the system account.

Added Admin account and a test User account to seed data, refer to Database Documentation for latest dump (I just update v3.1.2 cuz it's a minor change)

**Comment by Kyewn** [comment]
Looking good, the admin and user account passwords are?

**Comment by Vaneryn** [comment]
> Looking good, the admin and user account passwords are?

in discord pin
